### ISSUE TITLE
ST3 Package

### ISSUE THREAD

**Issue by iToto** [kemayo/sublime-text-2-goto-documentation#25]
Can't seem to find this package on ST3. Is it only available through manual install?

**Comment by theoretick** [comment]
No package that I know of but seems to work like a charm in ST3, just tried it.

**Comment by iToto** [comment]
yeah same. Just thought maybe there would be a package for it.

**Comment by steinmb** [comment]
If it works we should have a package that validate in http://www.caniswitchtosublimetext3.com

**Comment by iToto** [comment]
:+1:

**Comment by jsborjesson** [comment]
It works perfectly in ST3 for me as well.

**Comment by steinmb** [comment]
Good news/ What does it takes to get it tagged in https://sublime.wbond.net/ as ST3 complaint?

**Comment by jsborjesson** [comment]
I believe it's just a matter of forking wbond/package_control_channel and changing 

```
"sublime_text": "<3000"
```

to

```
"sublime_text": "*"
```

I haven't done this myself but it seems easy enough.

**Comment by steven-pribilinskiy** [comment]
how is that it's working for you?
I got an error in both cases (when installing through package control and also through git clone)
the error:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'url'
```

**Comment by jsborjesson** [comment]
That's too bad. It could be an OS issue, it's running perfectly on OSX, but
I see you're running Windows.

**Comment by theoretick** [comment]
Yes, tested on OSX, do not know if its working on Windows

**Comment by steven-pribilinskiy** [comment]
There's an error on Windows OS and i'm not a python guy to fix that :(

**Comment by nicolashohm** [comment]
i use it on Win 7 and it works great with php.net

**Comment by steven-pribilinskiy** [comment]
just tried to access the docs in following php code

```
<?php
print_r($_GET);
```

that is expected to jump to 

> http://php.net/$_GET

but instead got this same error:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'url'
```

OS: Windows 8 x64

**Comment by nicolashohm** [comment]
strange, maybe a win 8 problem, i tried your example and it works perfect
Win 7 x64 ST3047

**Comment by nicolashohm** [comment]
Back to topic, Goto Documenation is now available via Package Control :)
