### ISSUE TITLE
Better JavaScript (centric) search  

### ISSUE THREAD

**Issue by kostasx** [kemayo/sublime-text-2-goto-documentation#31]
For a more javascript-centric search on Mozilla's developer link, embed an '&topic=js' at the search query string:

gotodocumentation.py#101

From:

open_url("https://developer.mozilla.org/en-US/search?q=%s" % keyword)

To:

open_url("https://developer.mozilla.org/en-US/search?q=%s" % keyword + "&topic=js")

**Comment by kemayo** [comment]
Okay, ea6dfa2 does this.
