### ISSUE TITLE
Choose which browser to open documentation in?

### ISSUE THREAD

**Issue by EdgeCaseBerg** [kemayo/sublime-text-2-goto-documentation#43]
Morning, 

I'm running Linux Mint and just installed this package. I like it a lot. The only thing is that I use chromium as my default browser but the package opens firefox? 

It is not immediately apparent to me how to change this, is there a way and I'm just missing it?

**Comment by EdgeCaseBerg** [comment]
Nevermind, this is not something your plugin decides. 

However, If anyone is interested on how to do it:
1. open `/usr/lib/python2.7/webbrowser.py` (or 2.6)
2. find the `open` function (line ~60 for me)
3. replace `browser = get(name)` with `browser = get('/usr/bin/chromium %s')
4. save python file, restart sublime text.

**Comment by jeremytm** [comment]
This no longer works. On Mac OS t's still opening in Safari for me, even after updating both python2.6 and python2.7, and restarting Sublime.

**Comment by jeremytm** [comment]
Opening a web page using default python settings correctly opens Chrome for me:
`python -c "import webbrowser; webbrowser.open('https://www.google.com');"`

But GOTO Documentation is still opening in Firefox if installed, or Safari otherwise. How can I change the browser used on Mac OS?
